[package]
name = "manetsim"
version = "0.1.0"
edition = "2024"

[lib]
name = "manetsim"
path = "src/lib.rs"

[dependencies]
kiddo = "5.2.4"
rand_xoshiro = "0.8.0"
num-traits = "0.2.19"
rand = "*"
lazy_static = "1.5.0"
log = { version = "*" }
env_logger = "*"
rayon = "1.11.0"
linearize = { version = "*", features = ["derive"] }
thread_local = "1.1.9"
az = "1.3.0"
take_mut = "0.2.2"
