[package]
name = "slant"
version = "0.2.0"
edition = "2024"
description = "Simulator for Large Ad hoc Network Topologies"
repository = "https://code.murraygrov.es/MurrayGroves/SLANT"
license-file = "LICENSE.md"
keywords = ["simulator", "manet", "network"]
categories = ["simulation"]

[lib]
name = "slant"
path = "src/lib.rs"

[dependencies]
kiddo = "5.2.4"
rand_xoshiro = "0.8.0"
num-traits = "0.2.19"
rand = "0.10.0"
lazy_static = "1.5.0"
log = { version = "0.4", features = ["release_max_level_info"] }
env_logger = "0.11"
rayon = "1.11.0"
linearize = { version = "0.1", features = ["derive"] }
thread_local = "1.1.9"
az = "1.3.0"
serde = { version = "1.0.228", features = ["derive"] }

[features]
# Disables internal stat collection
disable_internal_stats = []
# Disables internal event collection
disable_internal_events = []

[[example]]
path = "examples/flood.rs"
name = "flood"

[profile.release-with-debug]
inherits = "release"
debug = true
